name: ci.deno

on: [push]

jobs:
  build:
    name: build.deno
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: system info
        run: |
          deno --version
          deno run script.deno/info.ts

      - name: security audit (ğŸ·)
        run: echo TODO

      - name: build modules (ğŸ·)
        run: deno run script.deno/build-all.ts

      - name: run tests (ğŸ·)
        run: echo TODO

      - name: count (project stats)
        run: echo TODO
