name: ci.deno

on: [push]

jobs:
  build:
    name: build and test (ğŸ· TODO)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: sys.info
        run: |
          deno --version
          deno run --allow-env script.deno/info.ts

      - name: (ğŸ·) ci.audit â† Software Supply Chain (Secure)
        run: echo TODO

      - name: (ğŸ·) ci.build â† bundle modules
        run: deno run script.deno/build-all.ts

      - name: (ğŸ·) ci.test â† unit tests
        run: echo TODO

      - name: ci.info â† count (stats) ğŸ·
        run: echo TODO

      - name: (ğŸ™) sample.deno
        run: deno run script.deno/sample.ts
