name: ci.deno

on: [push]

jobs:
  build:
    name: build.deno
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: system info
        run: |
          deno --version
          deno run script.deno/info.ts

      - name: build modules (ğŸ· todo)
        run: deno run script.deno/build.ts

      - name: run tests (ğŸ· todo)
        run: echo no-op
